[project]
name = "ai-hub-sharepoint-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pydantic>=2.11.9",
    "pydantic-settings>=2.11.0",
]
notebooks = [
    "ipykernel>=6.30.1",
]
